/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package space.crickets.authorize;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.junit4.SpringRunner;
import space.crickets.authorize.testhelpers.HelloController;

import static org.junit.Assert.*;

/**
 * Ensures the various annotations work.
 */
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {AuthorizeTest.TestConfig.class})
public class AuthorizeTest {

    @Configuration
    @Import(HelloController.class)
    public static class TestConfig {}

    @Autowired
    private HelloController subject;

    @Test public void testCheckScopes() {
        String response = subject.getGreetingByName_checkScopes("Roger", "");
        assertEquals("Hello Roger", response);
    }

    @Test public void testCheckScopesAndMatchName() {
        String response = subject.getGreetingByName_checkScopesAndMatchName("Roger", "");
        assertEquals("Hello Roger", response);
    }

    @Test public void testCheckScopesAndMatchNameAndCheckAge() {
        String response = subject.getGreetingByName_checkScopesAndMatchNameAndCheckAge("Roger", null,"");
        assertEquals("Hello Roger", response);
    }
}
